######################################################################
# Automatically generated by qmake (3.1) Wed May 13 14:37:28 2020
######################################################################

TEMPLATE = app # тип исполн€емого файла - .exe
TARGET = ex1 # им€ исполн€емого файла Ц ex1
INCLUDEPATH += .
QT += gui widgets
CONFIG += release # им€ поддиректории дл€ исполн€емого файла
DEFINES += QT_DEPRECATED_WARNINGS
# Input
SOURCES = ex1.cpp # им€ исходного файла программы
